INSERT INTO outlets (name, is_active) VALUES
('01. TAPLAU', true),
('02. AIRTAWAR', true),
('03. GP', true),
('04. BELIBIS', true),
('05. SITEBA', true),
('06. PASBAR', true),
('07. TH', true),
('08. ANDURING', true),
('09. JATI', true),
('10. AIRPACAH', true),
('11. LUBEG', true),
('12. BALAIBARU', true),
('13. CENDRAWASIH', true),
('14. SEBPDG', true),
('15. BANDARBUAT', true),
('16. AIRDINGIN', true),
('17. TABING', true),
('18. BELIMBING', true),
('19. RAWANG', true),
('20. LUBAY', true),
('21. PARAKLAWEH', true),
('22. LUBUKLINTAH', true),
('23. KASANG', true),
('24. BUNGUS', true),
('25. LUBUKALUNG', true),
('26. KURAITAJI', true),
('27. LOHONG', true),
('28. MANGGUNG', true),
('29. PAUHKAMBAR', true),
('30. SICINCIN', true),
('31. TANAHGARAM', true),
('32. SELAYO', true),
('33. GUNUNGTALANG', true),
('34. SUNGAISARIAK', true),
('35. SIMPANGRUMBIO', true),
('36. KAMBANG', true),
('GOWES', true),
('KITCHEN', true),
('TC', true),
('KANTOR', true)
ON CONFLICT (name) DO NOTHING;

